name: sounds_of_home_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.24.3
  - matplotlib=3.7.1
  - pandas
  - seaborn
  - tqdm
  - tkinter
  - pip
  - pip:
    - librosa
